Repository tarkalabs/tarka-ui-kit-ios, pull requests merged in 2024-07, with the labels that each got.

#129 Fix: TUIAppTopBar icon size issue
  Sources/TarkaUI/Components/App Bar/TUIAppTopBar.swift
  Sources/TarkaUI/Components/Base Components/IconButton/TUIIconButton.swift
Labels: bug

#131 Issue For SearchBar Auto Focus in TUIAppBar
  Sources/TarkaUI/Components/Search Bar/TUISearchBarViewModel.swift
Labels: bug

#132 Show done button in safearea when bottom block modifier is used
  Sources/TarkaUI/Modifiers/View+Modifiers.swift
  Sources/TarkaUI/View Modifiers/BottomMobileButtonBlock.swift
Labels: bug, Don't Merge, dependent

#134 Removed app top bar extension
  Sources/TarkaUI/Components/Base Components/CircularProgressView/TUICircularProgressView.swift
  Sources/TarkaUI/Extensions/View+NavigationBar.swift
Labels: Don't Merge, dependent
